### ISSUE TITLE
Fix "inputs" in GitLab Component Configuration

### ISSUE THREAD

**Issue by refoo0** [l3montree-dev/devguard-web#120]
There is a formatting issue: the inputs need to be shifted to the right. Here is the correct formatting:
 
```
include:
  - remote: "https://gitlab.com/l3montree/devguard/-/raw/main/templates/full.yml"
    inputs:
      asset_name: "..."
      token: "$DEVGUARD_TOKEN"

```

![Image](https://github.com/user-attachments/assets/c5cdd8d1-3eca-42d2-b81f-c1fe9ee6a03d)
